-- ============================================================
-- Retail Inventory & Order Management API - Database Setup
-- ============================================================
-- Run this script ONLY if you prefer manual SQL setup
-- instead of using EF Core Migrations.
-- ============================================================

USE master;
GO

IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = 'RetailDB')
BEGIN
    CREATE DATABASE RetailDB;
    PRINT 'Database RetailDB created.';
END
GO

USE RetailDB;
GO

-- ============================================================
-- TABLES
-- ============================================================

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Users]') AND type = 'U')
BEGIN
    CREATE TABLE [dbo].[Users] (
        [Id]           INT            IDENTITY(1,1)  NOT NULL,
        [Username]     NVARCHAR(100)  NOT NULL,
        [PasswordHash] NVARCHAR(MAX)  NOT NULL,
        [Role]         NVARCHAR(20)   NOT NULL,
        [CreatedAt]    DATETIME2      NOT NULL DEFAULT GETUTCDATE(),
        CONSTRAINT [PK_Users] PRIMARY KEY ([Id]),
        CONSTRAINT [UQ_Users_Username] UNIQUE ([Username])
    );
    PRINT 'Table Users created.';
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Products]') AND type = 'U')
BEGIN
    CREATE TABLE [dbo].[Products] (
        [Id]            INT             IDENTITY(1,1)  NOT NULL,
        [Name]          NVARCHAR(200)   NOT NULL,
        [Description]   NVARCHAR(1000)  NOT NULL DEFAULT '',
        [Price]         DECIMAL(18,2)   NOT NULL,
        [StockQuantity] INT             NOT NULL DEFAULT 0,
        [CreatedAt]     DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
        [UpdatedAt]     DATETIME2       NOT NULL DEFAULT GETUTCDATE(),
        CONSTRAINT [PK_Products] PRIMARY KEY ([Id])
    );
    PRINT 'Table Products created.';
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Orders]') AND type = 'U')
BEGIN
    CREATE TABLE [dbo].[Orders] (
        [Id]          INT           IDENTITY(1,1)  NOT NULL,
        [UserId]      INT           NOT NULL,
        [TotalAmount] DECIMAL(18,2) NOT NULL,
        [Status]      NVARCHAR(50)  NOT NULL DEFAULT 'Pending',
        [CreatedAt]   DATETIME2     NOT NULL DEFAULT GETUTCDATE(),
        CONSTRAINT [PK_Orders] PRIMARY KEY ([Id]),
        CONSTRAINT [FK_Orders_Users] FOREIGN KEY ([UserId]) REFERENCES [dbo].[Users]([Id])
    );
    PRINT 'Table Orders created.';
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[OrderItems]') AND type = 'U')
BEGIN
    CREATE TABLE [dbo].[OrderItems] (
        [Id]        INT           IDENTITY(1,1)  NOT NULL,
        [OrderId]   INT           NOT NULL,
        [ProductId] INT           NOT NULL,
        [Quantity]  INT           NOT NULL,
        [UnitPrice] DECIMAL(18,2) NOT NULL,
        CONSTRAINT [PK_OrderItems] PRIMARY KEY ([Id]),
        CONSTRAINT [FK_OrderItems_Orders]   FOREIGN KEY ([OrderId])   REFERENCES [dbo].[Orders]([Id])   ON DELETE CASCADE,
        CONSTRAINT [FK_OrderItems_Products] FOREIGN KEY ([ProductId]) REFERENCES [dbo].[Products]([Id])
    );
    PRINT 'Table OrderItems created.';
END
GO

-- ============================================================
-- INDEXES
-- ============================================================

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_Orders_UserId')
    CREATE INDEX [IX_Orders_UserId] ON [dbo].[Orders] ([UserId]);
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_OrderItems_OrderId')
    CREATE INDEX [IX_OrderItems_OrderId] ON [dbo].[OrderItems] ([OrderId]);
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_OrderItems_ProductId')
    CREATE INDEX [IX_OrderItems_ProductId] ON [dbo].[OrderItems] ([ProductId]);
GO

-- ============================================================
-- SEED DATA
-- NOTE: Passwords are BCrypt hashes. Plaintext passwords:
--   admin     -> Admin@123
--   customer1 -> Customer@123
--   customer2 -> Customer@123
-- The EF migration re-generates these hashes at build time.
-- Insert seed users only if table is empty.
-- ============================================================

IF NOT EXISTS (SELECT 1 FROM [dbo].[Users])
BEGIN
    -- NOTE: Replace the PasswordHash values below with actual BCrypt hashes
    -- generated by running the application once (EF seeding handles this automatically).
    -- These are placeholder values. Use the EF migration approach for real hashes.
    INSERT INTO [dbo].[Users] ([Username], [PasswordHash], [Role], [CreatedAt])
    VALUES
        ('admin',     'RUN_APP_TO_GENERATE_HASH', 'Admin',    '2024-01-01 00:00:00'),
        ('customer1', 'RUN_APP_TO_GENERATE_HASH', 'Customer', '2024-01-01 00:00:00'),
        ('customer2', 'RUN_APP_TO_GENERATE_HASH', 'Customer', '2024-01-01 00:00:00');
    PRINT 'Seed users inserted. Update PasswordHash values with real BCrypt hashes.';
END
GO

IF NOT EXISTS (SELECT 1 FROM [dbo].[Products])
BEGIN
    INSERT INTO [dbo].[Products] ([Name], [Description], [Price], [StockQuantity], [CreatedAt], [UpdatedAt])
    VALUES
        ('Laptop Pro 15',      'High-performance laptop with 15-inch display',              1299.99, 50,  '2024-01-01 00:00:00', '2024-01-01 00:00:00'),
        ('Wireless Mouse',     'Ergonomic wireless mouse with long battery life',             29.99, 200, '2024-01-01 00:00:00', '2024-01-01 00:00:00'),
        ('Mechanical Keyboard','RGB backlit mechanical keyboard with Cherry MX switches',     89.99, 100, '2024-01-01 00:00:00', '2024-01-01 00:00:00'),
        ('USB-C Hub',          '7-in-1 USB-C hub with HDMI, USB 3.0, and SD card reader',   49.99, 150, '2024-01-01 00:00:00', '2024-01-01 00:00:00'),
        ('4K Monitor',         '27-inch 4K UHD IPS monitor with HDR support',               449.99, 30, '2024-01-01 00:00:00', '2024-01-01 00:00:00');
    PRINT 'Seed products inserted.';
END
GO

PRINT 'Database setup complete.';
GO
